### PR TITLE
Removed idea list from readme

### PR DESCRIPTION
**Pull request by its-everdred**
Deleted idea list from readme and re-ordered steps.
Instead of listing ideas in the readme, we will have users create issues with project names and descriptions.

### CODE REVIEW

**Review by its-everdred — COMMENTED** [review]
This is the greatest change that has happened thus far.

**Comment by FreekingDean** [comment]
Was drunkdads.com an actual idea or a placeholder?

**Comment by its-everdred** [comment]
Yes.

**Comment by FreekingDean** [comment]
So, I think you should open the issue, first so we actually move the idea to issues before merging this in :)

**Comment by its-everdred** [comment]
I just created the issue.

**Comment by FreekingDean** [comment]
You are the issue.

**Review by FreekingDean — APPROVED** [review]
👍

**Pull request merged**
